### ISSUE TITLE
Stock alert add option auto displays a preset template row not sure if it should show a form to choose which stock I want to add

### ISSUE THREAD

**Issue by rajeevnadgauda** [vinyasmusic/price-alert#4]

**Comment by pyvinyas** [comment]
That option is intended as an example of what can be entered. Since I don't want to restrict the user from choosing the scrip symbol it's a free form box as of now. 
I need to put validation on whether the symbol is valid or not though.

**Comment by rajeevnadgauda** [comment]
Cool
